server:
  port: 9200
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin123@10.110.59.21:7100/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
feign:
  client:
    config:
      default:
        loggerLevel: FULL 
logging:
  appender: file
  path: /data/logs/
  level:
    com.netflix: warn
    com.zhht.cloud.UserFeignClient: debug
  pattern:
   level: info